export type ComponentSpec = {
  dimensions: string
  weight?: string
  material?: string
  voltage?: string
  temperature?: string
  interface?: string
  mfrPart?: string
  package?: string
}

export type PartInfo = {
  name: string
  branch: string
  func: string
  loc: string
  role: string
  details: string[]
  specs?: ComponentSpec
  kind: 'hardware' | 'dsp'
  focus: [number, number, number]
  cam?: [number, number, number]
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const F = (x: number, y: number, z: number, _cam?: [number, number, number]): PartInfo['focus'] => [x, y, z]

export const PARTS: Record<string, PartInfo> = {
  /* ================= ENCLOSURE ================= */
  'upper-enclosure': {
    name: 'UPPER ENCLOSURE (LID)',
    branch: 'Enclosure › Upper Shell',
    kind: 'hardware',
    func: 'Closes and protects the assembly; carries the external control apertures, LED light-pipe window, protective button bezels and the two microphone port recesses.',
    loc: 'Upper half of the two-piece enclosure, split line at Y = +8.4 mm.',
    role: 'Primary environmental barrier for the operator-facing side of SHIELD-COM and the mechanical datum for all human interfaces.',
    specs: {
      dimensions: '72.0 × 50.0 × 9.8 mm (lid height)',
      weight: '24.2 g',
      material: 'SABIC Cycoloy PC/ABS GF20 (20% glass-fill), matte graphite',
      temperature: '-40 °C to +85 °C operational',
      interface: 'Interlocking silicone gasket channel + 4× M2 corner screws',
    },
    details: [
      'Glass-filled polycarbonate / ABS, 2.2 mm nominal wall',
      'Recessed SOS + MARK apertures with raised guard bezels',
      'Moulded light-pipe bores for 4 status indicators',
      'Two sealed microphone port recesses with stainless mesh retainers',
      '4× M2 screw bosses with brass heat-set threaded inserts',
      'Seats on a 1.2 mm silicone gasket (IP-class sealing)',
    ],
    focus: F(0, 1.4, 0, [0.6, 1.1, 1.0]),
  },
  'lower-enclosure': {
    name: 'LOWER ENCLOSURE (BASE)',
    branch: 'Enclosure › Lower Shell',
    kind: 'hardware',
    func: 'Carries the internal frame, the battery compartment, the PCB stack, the USB-C service port and the protected audio connector recess.',
    loc: 'Lower half of the two-piece enclosure, floor at Y = −12.5 mm.',
    role: 'Structural backbone of the module; locates every internal sub-assembly and provides the mounting interface to the host radio / harness.',
    specs: {
      dimensions: '72.0 × 50.0 × 16.7 mm (total module 26.5 mm)',
      weight: '31.5 g',
      material: 'SABIC Cycoloy PC/ABS GF20 + co-moulded TPE 70A bumpers',
      temperature: '-40 °C to +85 °C',
      interface: '2× M3 threaded inserts for PALS/MOLLE clip; USB-C + 4-pin audio bay',
    },
    details: [
      'Glass-filled polycarbonate / ABS, 2.2 mm wall, 2.5 mm floor',
      'Integral screw bosses, battery pocket and cable channels',
      'Moulded-in grip ribs and TPE corner impact bumpers',
      'Recessed connector bay (USB-C service / charge)',
      'Protected 4-pin circular audio bay with 6.7 mm deep shroud',
      '2× M3 threaded inserts for the mounting bracket',
    ],
    focus: F(0, -0.4, 0, [0.8, 0.5, 1.0]),
  },
  gasket: {
    name: 'ENVIRONMENTAL GASKET',
    branch: 'Mechanical › Gaskets',
    kind: 'hardware',
    func: 'Compresses between the lid and the base along the full perimeter split line to seal against dust, rain and splash.',
    loc: 'Perimeter groove on the crown of the lower-shell walls, Y = +7.2 … +8.4 mm.',
    role: 'Provides the ingress-protection seal and pre-loads the enclosure screws to resist loosening under vibration.',
    details: [
      'Silicone elastomer, 60 Shore A, 1.6 × 1.2 mm cross-section',
      'Continuous closed-cell perimeter ring, ~25 % compression',
      'Also acts as an acoustic break between the two shells',
    ],
    focus: F(-3.4, 0.78, 0, [1.0, 0.7, 0.9]),
  },
  'internal-frame': {
    name: 'INTERNAL FRAME',
    branch: 'Mechanical › Internal Frame',
    kind: 'hardware',
    func: 'Rigid moulded chassis that captures the battery, supports the main PCB on four standoffs, routes cables and transfers impact loads into the enclosure walls.',
    loc: 'Inside the lower shell, spanning Y = −10.0 … +2.8 mm.',
    role: 'Single structural interposer between the electronics and the enclosure – it prevents PCB flex, isolates the battery and keeps all wiring captive.',
    details: [
      'Injection-moulded PC/ABS, 1.2 mm ribs, 5.8 mm PCB standoff height',
      'Battery pocket with 4 locating ribs + retention shoulders',
      'Cable channel along the +Z wall with 2 moulded clips',
      '4 standoff bosses with M2 threaded brass inserts',
      'Transfers drop/shock loads into the corner bumpers',
    ],
    focus: F(0, -0.35, 0, [0.9, 0.6, 1.0]),
  },
  screws: {
    name: 'ENCLOSURE & PCB SCREWS',
    branch: 'Mechanical › Screws',
    kind: 'hardware',
    func: 'Clamp the lid, gasket and base together and retain the main PCB on the internal-frame standoffs.',
    loc: '4× M2 × 14 mm at the enclosure corners; 4× M2 × 5 mm through the PCB into the frame bosses.',
    role: 'Provide the controlled gasket compression and the vibration-resistant fastening required for field service.',
    details: [
      'M2 × 14 mm countersunk stainless, 4 off (enclosure)',
      'M2 × 5 mm pan-head stainless, 4 off (PCB)',
      'Threaded into brass heat-set inserts, 0.6 N·m torque',
      'Captured in the lid – cannot be lost during battery service',
    ],
    focus: F(3.15, -0.2, 2.12, [1.0, 0.4, 0.9]),
  },
  standoffs: {
    name: 'PCB STANDOFFS',
    branch: 'Mechanical › Standoffs',
    kind: 'hardware',
    func: 'Set the precise 5.8 mm gap between the internal frame and the underside of the main PCB and carry the PCB retention screws.',
    loc: 'Four positions at the PCB corners, between the frame bosses and the PCB underside.',
    role: 'Define the PCB mechanical datum, keep solder-side components clear of the battery and provide a low-impedance chassis return.',
    details: [
      'M2 hex brass standoffs, 5.8 mm body, 4 off',
      'Sits on moulded frame bosses, M2 thread both ends',
      'Maintains 4.2 mm clearance to the battery surface',
    ],
    focus: F(2.85, 0.0, -1.85, [1.0, 0.6, 1.0]),
  },
  'mounting-bracket': {
    name: 'MOUNTING BRACKET',
    branch: 'Mechanical › Mounting Brackets',
    kind: 'hardware',
    func: 'Detachable stainless bracket that clamps SHIELD-COM to a vest, MOLLE/PALS webbing, harness strap or the host-radio belt clip.',
    loc: 'Underside of the lower enclosure, Y = −14.1 … −12.5 mm.',
    role: 'The mounting / interface mechanism that makes SHIELD-COM an add-on accessory rather than a handheld device.',
    details: [
      '1.4 mm stainless steel, black oxide finish',
      '2× M3 × 6 mm into threaded inserts in the base',
      'Spring-steel PALS retention arms, 25 mm webbing pitch',
      'Removable without opening the enclosure',
    ],
    focus: F(0.2, -1.35, 0, [0.9, -0.2, 1.0]),
  },
  'threaded-inserts': {
    name: 'THREADED INSERTS',
    branch: 'Mechanical › Fastening',
    kind: 'hardware',
    func: 'Brass heat-set inserts that provide durable, repeat-service metal threads in the polymer bosses.',
    loc: '4× in the lid screw bosses, 4× in the frame standoff bosses, 2× M3 in the base for the bracket.',
    role: 'Allow the enclosure and PCB to be opened and re-closed many times in the field without thread wear in the plastic.',
    details: [
      'M2 × 4 mm and M3 × 5 mm knurled brass inserts',
      'Ultrasonic / heat-set installation',
      'Rated for > 25 service cycles',
    ],
    focus: F(-3.15, 1.05, 2.12, [1.0, 0.7, 0.9]),
  },

  /* ================= MAIN PCB ================= */
  'main-pcb': {
    name: 'MAIN PCB',
    branch: 'Main PCB',
    kind: 'hardware',
    func: 'Custom 4-layer rigid PCB that interconnects the ESP32 processing module, the audio conversion chain, the power subsystem, the controls and all external connectors.',
    loc: 'Mounted on the internal-frame standoffs, Y = +2.8 … +4.4 mm.',
    role: 'The physical and electrical backbone of SHIELD-COM – every other electronic assembly lands on this board.',
    specs: {
      dimensions: '60.5 × 36.0 × 1.6 mm',
      weight: '7.8 g',
      material: 'FR-4 High-Tg (Tg > 170 °C), matte-black solder mask, ENIG gold',
      voltage: '3.3 V Digital, 1.8 V Analogue Star-Rail, 3.7 V VBAT',
      temperature: '-40 °C to +105 °C',
      interface: 'Layer Stack: L1 SIG / L2 GND / L3 PWR / L4 SIG',
    },
    details: [
      '60.5 × 36 × 1.6 mm, 4-layer FR-4, ENIG finish',
      'Dedicated ground plane + split analogue / digital domains',
      'Controlled 4-layer stackup for I²S and USB routing',
      '4× M2 mounting holes, 4 mm keep-out for the acoustic ports',
      'Test points for I²S, 3V3, 1V8 and battery sense',
    ],
    focus: F(0, 0.44, 0, [0.7, 1.1, 0.9]),
  },
  esp32: {
    name: 'ESP32 PROCESSING MODULE',
    branch: 'Main PCB › ESP32',
    kind: 'hardware',
    func: 'Real-time embedded processing: runs the audio front end, the voice-enhancement / noise-suppression DSP pipeline, button handling, LED status management and the interface/control state machine.',
    loc: 'Main PCB, top side, centre-right (X = +5.5 mm, Z = −1.0 mm).',
    role: 'Runs SHIELD-COM’s audio enhancement / noise-suppression processing and system-control logic. The AI/DSP functions are software executing on this device – there is no separate "AI chip".',
    specs: {
      mfrPart: 'Espressif ESP32-S3-WROOM-1 (N16R8)',
      dimensions: '25.5 × 18.0 × 3.1 mm (official mechanical dwg)',
      package: 'Castellated SMD module, 1.27 mm pitch, 41 pins',
      voltage: '3.0 V to 3.6 V (Nominal 3.3 V)',
      temperature: '-40 °C to +85 °C',
      interface: '2× I²S, USB-OTG, SPI, I²C, 240 MHz Dual-Core Xtensa LX7 + Vector DSP',
    },
    details: [
      'Espressif ESP32-S3-WROOM-1 (N16R8) — per datasheet 25.5 × 18.0 × 3.1 mm',
      'Dual-core Xtensa LX7 @ 240 MHz, 512 KB SRAM, 16 MB flash + 8 MB PSRAM',
      '1.27 mm castellated half-holes; integral PCB antenna at one end',
      '2× I²S, USB-OTG, SDIO, SPI, I²C, UART — Espressif lists audio devices and speech recognition as target applications',
      'Wi-Fi 802.11 b/g/n + BT 5 (LE) used for configuration/service only',
      'Voice-enhancement DSP load ≈ 55 % of one core @ 16 kHz mono',
    ],
    focus: F(0.55, 0.62, -0.1, [0.8, 1.0, 0.9]),
  },
  'esp32-shield': {
    name: 'ESP32 RF SHIELD / ANTENNA REGION',
    branch: 'Main PCB › ESP32',
    kind: 'hardware',
    func: 'Metal shield can over the ESP32 RF and digital section, plus the module antenna keep-out and the PCB antenna feed region.',
    loc: 'Directly on top of the ESP32 module, Y = +5.3 … +7.0 mm.',
    role: 'Contains the module’s own Wi-Fi / BLE radio and protects the sensitive RF and high-speed digital nodes from the audio and power sections.',
    details: [
      'Module-integral shield can ≈ 17.6 × 16.8 mm over the RF + digital section',
      '8.5 mm antenna region left uncovered per Espressif keep-out guidance',
      'Grounded to the module pad ring; PCB keep-out beyond the module edge has no copper',
      'RF is used for service & configuration only – the soldier radio remains the only RF communication path',
    ],
    focus: F(0.55, 0.72, -0.1, [0.8, 1.1, 0.9]),
  },
  'audio-adc': {
    name: 'AUDIO ADC (INPUT CONVERSION)',
    branch: 'Main PCB › Audio Codec / ADC',
    kind: 'hardware',
    func: 'Converts the analogue / PDM microphone signals into a digital I²S stream and applies input gain, anti-alias filtering and DC blocking before the ESP32.',
    loc: 'Main PCB, top side, audio section (X = −18.5 mm, Z = +3.5 mm).',
    role: 'The mandatory analogue-to-digital interface between the microphones and the ESP32 – the ESP32 never connects directly to a raw microphone.',
    specs: {
      mfrPart: 'Everest Semiconductor ES7210 (4-Ch 24-bit ADC)',
      dimensions: '4.0 × 4.0 × 0.9 mm',
      package: 'QFN-20 (0.5 mm lead pitch)',
      voltage: '3.3 V (analogue 1.8 V filtered)',
      interface: 'I²S / TDM master/slave, 102 dB SNR, programmable PGA',
    },
    details: [
      'ES7210 4-ch stereo/multimic ADC, QFN-20, 4 × 4 mm',
      '24-bit, 8 – 96 kHz, 102 dB(A) dynamic range',
      'I²S / TDM digital output straight into the ESP32 I²S port',
      'Programmable PGA 0 – 36 dB, integrated anti-alias filter',
      'Single 3.3 V rail with a dedicated 1.8 V analogue LDO',
    ],
    focus: F(-1.85, 0.5, 0.35, [0.7, 1.0, 0.8]),
  },
  'audio-dac': {
    name: 'AUDIO DAC / OUTPUT AMPLIFIER',
    branch: 'Main PCB › Audio Codec / DAC',
    kind: 'hardware',
    func: 'Converts the processed digital voice stream back to analogue and drives the line / headset output toward the host radio accessory port.',
    loc: 'Main PCB, top side, audio section (X = −18.5 mm, Z = −8.5 mm).',
    role: 'Final stage of the physical signal chain: delivers the enhanced, noise-suppressed voice to the radio / headset interface.',
    specs: {
      mfrPart: 'Everest Semiconductor ES8311 (Low-Power Audio Codec)',
      dimensions: '3.0 × 3.0 × 0.75 mm',
      package: 'QFN-20 (0.4 mm lead pitch)',
      voltage: '1.8 V to 3.3 V (14 mW active power)',
      interface: 'I²S, mono DAC + headphone/line driver, 100 dB SNR',
    },
    details: [
      'ES8311-class low-power audio DAC + line/headphone driver',
      '24-bit, 8 – 96 kHz, 100 dB SNR, −80 dB THD+N',
      'I²S input from the ESP32, single-ended line output',
      'Pop/click suppression and soft mute on PTT transitions',
      'Output level set to the host-radio mic-input sensitivity',
    ],
    focus: F(-1.85, 0.5, -0.85, [0.7, 1.0, 0.9]),
  },
  'analog-filter': {
    name: 'ANALOG FILTERING / COUPLING NETWORK',
    branch: 'Main PCB › Audio Codec',
    kind: 'hardware',
    func: 'Passive RC input filters, AC-coupling capacitors, bias networks and EMI chokes that condition the microphone and output signals around the ADC and DAC.',
    loc: 'Main PCB, clustered between the microphone inputs and the ADC, and between the DAC and the output connector.',
    role: 'Guarantees that only conditioned, band-limited, DC-blocked audio reaches the converters and leaves the module.',
    details: [
      'Differential RC anti-alias filters, fc ≈ 24 kHz',
      'AC-coupling: 1 µF X7R film / X7R ceramic',
      'Common-mode chokes on the output line for EMI',
      'All parts in the analogue keep-out, 3 mm from digital traces',
    ],
    focus: F(-1.2, 0.5, 0.2, [0.7, 1.0, 0.8]),
  },
  'power-mgmt': {
    name: 'POWER-MANAGEMENT / CHARGE IC',
    branch: 'Main PCB › Power Management',
    kind: 'hardware',
    func: 'Manages battery charging from USB-C, power-path selection, fuel-gauging and system power sequencing.',
    loc: 'Main PCB, power zone, left side (X = −28.5 mm, Z = −3.0 mm).',
    role: 'Keeps SHIELD-COM running for a full mission from its internal cell and recharges safely from any 5 V source.',
    specs: {
      mfrPart: 'Microchip MCP73871 (Advanced System Power-Path Li-Ion Charger)',
      dimensions: '4.0 × 4.0 × 0.9 mm',
      package: 'QFN-20 (0.5 mm pitch)',
      voltage: 'VIN 4.35 V to 6.0 V (USB-C 5V VBUS), VBAT 4.20 V',
      interface: 'Auto Power-Path: module operates while dead battery recharges',
    },
    details: [
      'MCP73871 linear charger + dynamic system power-path manager, QFN-20',
      '1 A charge current, JEITA temperature profile',
      'Dynamic power-path: system can run with a depleted cell',
      'I²C fuel gauge + cell temperature monitor',
      'Input over-voltage / reverse protection on VBUS',
    ],
    focus: F(-2.85, 0.5, -0.3, [0.7, 1.0, 0.9]),
  },
  'buck-reg': {
    name: '3.3 V BUCK REGULATOR',
    branch: 'Main PCB › Regulators',
    kind: 'hardware',
    func: 'High-efficiency step-down converter producing the main 3.3 V digital / I/O rail from the single-cell Li-ion input.',
    loc: 'Main PCB, power zone (X = −28.5 mm, Z = +5.5 mm).',
    role: 'Supplies the ESP32, the audio converters and the digital logic with a stable, low-ripple rail across the whole battery range.',
    specs: {
      mfrPart: 'Texas Instruments TPS62260 (2.25 MHz Synchronous Step-Down)',
      dimensions: '2.9 × 2.8 × 1.1 mm (SOT-23-6) / 2.0 × 2.0 mm (WSON)',
      package: 'SOT-23-6 / WSON-6',
      voltage: 'VIN 2.0 V to 6.0 V, VOUT 3.3 V fixed/adj @ 600 mA',
      interface: '95% peak efficiency, 15 µA quiescent, <12 mVpp audio ripple',
    },
    details: [
      'TPS62260-class synchronous buck, 2.25 MHz, QFN-6',
      'Up to 95 % efficiency, 15 µA quiescent',
      '2.2 µH shielded inductor, 10 µF X7R output',
      'Output ripple < 12 mV pp (audio-band critical)',
    ],
    focus: F(-2.85, 0.5, 0.55, [0.7, 1.0, 0.8]),
  },
  'ldo-reg': {
    name: 'LOW-NOISE ANALOG LDO',
    branch: 'Main PCB › Regulators',
    kind: 'hardware',
    func: 'Ultra-low-noise linear regulator generating the dedicated analogue / microphone bias rail, isolated from the switching regulator.',
    loc: 'Main PCB, power zone (X = −22.0 mm, Z = +12.0 mm).',
    role: 'Protects the microphone and ADC front end from switching noise – critical for a noise-suppression product.',
    details: [
      'TPS7A20-class LDO, SOT-23-5, 1.8 V / 200 mA',
      '7 µV RMS output noise, 70 dB PSRR @ 1 kHz',
      'Separate star-routed analogue ground return',
      'Dedicated mic-bias RC filter (2.2 kΩ / 1 µF)',
    ],
    focus: F(-2.2, 0.5, 1.2, [0.7, 1.0, 0.8]),
  },
  inductor: {
    name: 'POWER INDUCTOR',
    branch: 'Main PCB › Regulators',
    kind: 'hardware',
    func: 'Energy-storage element of the 3.3 V buck converter.',
    loc: 'Main PCB, power zone, beside the buck regulator (X = −28.5 mm, Z = −9.5 mm).',
    role: 'Sets the converter ripple current and transient response; shielded construction keeps magnetic fields away from the audio front end.',
    details: [
      '2.2 µH ±20 %, 1.6 A Isat, magnetically shielded',
      '3.2 × 3.2 × 1.5 mm package',
      'Placed 12 mm from the microphone inputs by design rule',
    ],
    focus: F(-2.85, 0.55, -0.95, [0.7, 1.0, 0.9]),
  },
  flash: {
    name: 'NON-VOLATILE MEMORY (FLASH)',
    branch: 'Main PCB › Memory',
    kind: 'hardware',
    func: 'Stores firmware, configuration, acoustic calibration data and the short MARK event clips captured for later transmission.',
    loc: 'Main PCB, top side (X = +22.0 mm, Z = −12.0 mm).',
    role: 'Gives the MARK function a local buffer so an event can be captured even when the radio link is busy or unavailable.',
    specs: {
      mfrPart: 'Winbond W25Q128JVEIQ (128 Mbit / 16 MB Serial NOR)',
      dimensions: '6.0 × 5.0 × 0.75 mm',
      package: 'WSON-8 (8-pad flat leadless package)',
      voltage: '2.7 V to 3.6 V (Nominal 3.3 V)',
      interface: 'Standard / Dual / Quad-SPI @ 133 MHz (66 MB/s burst)',
    },
    details: [
      'Winbond W25Q128JV — 128 Mbit (16 MB) SPI NOR flash, WSON-8',
      'Quad-SPI @ 133 MHz, XIP capable for DSP model weighting',
      'Holds ≈ 20 minutes of 16 kHz ADPCM event audio buffer',
      'Wear-levelled event log with 32-bit CRC per audio segment',
    ],
    focus: F(2.2, 0.5, -1.2, [0.8, 1.0, 1.0]),
  },
  crystal: {
    name: '40 MHz REFERENCE CRYSTAL',
    branch: 'Main PCB › Passive Components',
    kind: 'hardware',
    func: 'Precision clock reference for the ESP32 and the audio converters.',
    loc: 'Main PCB, top side, adjacent to the ESP32 module (X = +0.5 mm, Z = +8.0 mm).',
    role: 'Provides the jitter-free master clock that both the digital audio interfaces and the radio-free timing of the DSP pipeline depend on.',
    details: [
      '40 MHz ±10 ppm, 8 pF load, 2.5 × 2.0 mm',
      'Ground-shielded keep-out, guard ring on layer 1',
      'Audio MCLK derived by integer division (no fractional PLL)',
    ],
    focus: F(0.05, 0.5, 0.8, [0.8, 1.1, 0.9]),
  },
  passives: {
    name: 'PASSIVE COMPONENTS',
    branch: 'Main PCB › Passive Components',
    kind: 'hardware',
    func: 'Decoupling, bulk storage, bias, termination, filtering and pull-up networks distributed across every functional block.',
    loc: 'Main PCB, both sides, clustered around each active device.',
    role: 'Make the silicon behave: local decoupling is what allows a 240 MHz DSP and a 100 dB audio path to coexist on one 62 × 36 mm board.',
    details: [
      '≈ 180 discrete parts, 0402 / 0603 / 0805',
      '100 nF X7R decoupling at every supply pin (< 2 mm loop)',
      '1 × 47 µF + 2 × 10 µF bulk on 3V3 and VBAT',
      '1 % thin-film resistors in the analogue gain stages',
    ],
    focus: F(-0.6, 0.48, 0.6, [0.7, 1.1, 0.9]),
  },
  'esd-protection': {
    name: 'ESD / TRANSIENT PROTECTION',
    branch: 'Main PCB › Protection',
    kind: 'hardware',
    func: 'ESD suppression and line termination on the externally reachable audio and USB lines.',
    loc: 'Main PCB, immediately behind the audio output and USB-C connectors.',
    role: 'Protects the ADC/DAC, the ESP32 USB port and the power path against cable-borne ESD in the field.',
    details: [
      '4-channel TVS / ESD array, ±15 kV air, ±8 kV contact',
      'Series 22 Ω resistors on USB D+/D−',
      'Polyfuse + TVS on VBUS, 6 V clamp',
    ],
    focus: F(2.55, 0.5, 0.55, [0.9, 1.0, 1.0]),
  },
  'test-points': {
    name: 'TEST POINTS / SERVICE PADS',
    branch: 'Main PCB › Test Points',
    kind: 'hardware',
    func: 'Gold-plated probe pads for production test, I²S monitoring, rail measurement and boundary-scan service.',
    loc: 'Main PCB, top side, front area (X = +3.0 mm, Z = +13.5 mm).',
    role: 'Enable bed-of-nails production test and field diagnostics without disassembling the module.',
    details: [
      '8 × 0.9 mm ENIG pads on a 1.27 mm grid',
      'I²S_BCLK / I²S_WS / I²S_DOUT / 3V3 / 1V8 / VBAT / GND / BOOT',
      'Silkscreen reference designators beside each pad',
    ],
    focus: F(0.3, 0.46, 1.4, [0.8, 1.1, 0.9]),
  },
  'usb-c': {
    name: 'USB-C SERVICE / CHARGE CONNECTOR',
    branch: 'Main PCB › Connectors',
    kind: 'hardware',
    func: '5 V charging input, firmware update, configuration and wired diagnostics.',
    loc: 'Main PCB, left edge (X = −27.5 mm, Z = −13.0 mm); recessed behind the lower-shell port bay.',
    role: 'The only service port; recessed 4.8 mm into the base so a plugged cable is protected from impact.',
    specs: {
      mfrPart: 'GCT USB4085 / Amphenol 16-pin USB Type-C Receptacle',
      dimensions: '8.94 × 7.35 × 3.16 mm',
      package: 'Mid-mount SMT with 4 through-hole grounding shell tabs',
      voltage: '5.0 V VBUS (1.5 A charging capability, CC 5.1 kΩ pulldowns)',
      interface: 'USB 2.0 High-Speed D+/D- direct to ESP32-S3 internal USB PHY',
    },
    details: [
      'USB 2.0 Type-C receptacle, 16-pin, SMT + through-hole shell',
      'USB Serial/JTAG on the ESP32-S3 – no external UART bridge',
      'CC resistors for 5 V / 1.5 A negotiation',
      'ESD-protected, 4.8 mm recess in the enclosure wall',
    ],
    focus: F(-2.75, 0.6, -1.3, [0.6, 0.9, 1.0]),
  },
  'audio-jack': {
    name: 'AUDIO OUTPUT CONNECTOR',
    branch: 'External Interfaces',
    kind: 'hardware',
    func: 'Rugged 4-pin circular panel connector carrying the processed transmit audio to the host radio (and returning PTT / radio audio where fitted).',
    loc: 'Panel-mounted in the protected bay on the +X wall of the lower shell (Y = +3.85 mm, Z = +5.5 mm).',
    role: 'The physical boundary between SHIELD-COM’s audio processing and the existing radio – SHIELD-COM does not transmit; it feeds clean audio to the radio.',
    specs: {
      mfrPart: 'Amphenol / Binder 712 Series IP67 Subminiature circular',
      dimensions: 'Ø 8.5 mm panel flange, 6.7 mm deep protective recess',
      material: 'Nickel-plated brass shell with gold-plated brass contacts',
      interface: 'Pinout: TX_AUDIO_OUT / GND / PTT_SENSE / RADIO_IN',
      package: 'IP67 waterproof mating with internal O-ring seal',
    },
    details: [
      '4-pin circular panel socket, 6.2 mm bay, gold-plated contacts',
      '6.7 mm deep protective shroud, O-ring sealed flange',
      'Pin-out: TX_AUDIO / GND / PTT_SENSE / RADIO_AUDIO',
      'Short internal 4-conductor harness to PCB header J2',
    ],
    focus: F(3.4, 0.4, 0.55, [1.0, 0.5, 0.8]),
  },
  'battery-connector': {
    name: 'BATTERY CONNECTOR (J1)',
    branch: 'Main PCB › Connectors',
    kind: 'hardware',
    func: 'Polarised 2-pin interface between the removable Li-ion pack and the PCB power path.',
    loc: 'Main PCB, top side, rear-left (X = −25.5 mm, Z = +12.5 mm).',
    role: 'Allows the battery to be replaced in the field without soldering, and guarantees correct polarity mechanically.',
    details: [
      'JST-PH / Molex PicoBlade compatible, 2.0 mm pitch',
      'Polarised shroud, positive latch, 3 A rating',
      'Gold-plated contacts, strain-relieved 22 AWG leads',
    ],
    focus: F(-2.55, 0.6, 1.25, [0.7, 1.0, 0.9]),
  },
  'io-header': {
    name: 'DEBUG / SERVICE HEADER',
    branch: 'Main PCB › Connectors',
    kind: 'hardware',
    func: '1.27 mm pinned header for production programming, boundary scan and optional external PTT / accessory expansion.',
    loc: 'Main PCB, top side, front-right (X = +14.0 mm, Z = +13.5 mm).',
    role: 'Manufacturing and depot-level service access; not used during normal operation.',
    details: [
      '6-pin 1.27 mm dual-row header',
      'SWD / JTAG, UART0, BOOT, GND, 3V3',
      'Covered by the lid – accessed only with the module open',
    ],
    focus: F(1.4, 0.55, 1.35, [0.9, 1.1, 0.9]),
  },
  'status-leds': {
    name: 'STATUS LED ARRAY',
    branch: 'Status Indicators',
    kind: 'hardware',
    func: 'Four discrete indicators: POWER, SYSTEM / PROCESSING, SOS and MARK / RECORD.',
    loc: 'Main PCB, top side, rear edge (Z = −18.0 mm) under the light-pipe window.',
    role: 'Give the operator unambiguous, glove-visible confirmation of power state, DSP activity, emergency transmission and event capture.',
    details: [
      '4 × 0805 LEDs: green (PWR), blue (STAT), amber (SOS), red (MARK)',
      '2 mA drive, PWM dimmed for night-vision compatibility',
      'Coupled to moulded light pipes in the lid',
    ],
    focus: F(1.25, 0.5, -1.8, [0.7, 1.1, 0.9]),
  },
  'light-pipes': {
    name: 'LIGHT PIPES / INDICATOR WINDOW',
    branch: 'Status Indicators',
    kind: 'hardware',
    func: 'Four moulded optical light pipes that carry LED output to a single recessed, sealed window on the top face.',
    loc: 'Moulded into the lid, from the LED tops (Y = +5.0 mm) to the top surface (Y = +14.0 mm).',
    role: 'Move the indicators to a readable outward surface while keeping the electronics fully sealed behind the gasket.',
    details: [
      'Optical-grade PC light pipes, Ø 2.1 mm, 4 off',
      'Frosted diffuser window, 18 × 4.2 mm, UV stable',
      'Cross-talk baffles between adjacent pipes',
      'Window is ultrasonically welded into the lid, IP sealed',
    ],
    focus: F(1.25, 1.0, -1.86, [0.7, 1.2, 0.9]),
  },

  /* ================= AUDIO SYSTEM ================= */
  'mic-voice': {
    name: 'MEMS MICROPHONE – VOICE (MIC1)',
    branch: 'Audio System › MEMS Microphone',
    kind: 'hardware',
    func: 'Primary voice pickup: a top-port MEMS microphone sealed to a dedicated acoustic channel that exits on the operator-facing top face.',
    loc: 'Main PCB, top side, front-right (X = +29.0 mm, Z = +13.0 mm).',
    role: 'First element of the signal chain. Captures the operator’s voice with a short, well-defined acoustic path to the outside world.',
    specs: {
      mfrPart: 'Knowles SPU0410LR5H-QB (High-AOP Top-Port Analogue MEMS)',
      dimensions: '3.76 × 3.00 × 1.10 mm',
      package: '4-pad LGA with 0.84 mm acoustic sound port',
      voltage: '1.5 V to 3.6 V (120 µA consumption)',
      interface: 'Analogue differential output, 63 dB SNR, 128 dB SPL AOP',
    },
    details: [
      'Knowles SPU0410LR5H-QB top-port MEMS microphone, 3.76 × 3.0 × 1.1 mm',
      '63 dB SNR, −38 dBV/Pa, 128 dB SPL AOP',
      'Analogue output into the input filter network → ADC',
      'Solder-sealed port, silicone acoustic gasket to the lid',
      'Acoustic path: 0.9 mm port → 6 mm channel → 1.5 mm mesh',
    ],
    focus: F(2.72, 1.0, 1.3, [0.9, 1.0, 0.9]),
  },
  'mic-ref': {
    name: 'MEMS MICROPHONE – NOISE REFERENCE (MIC2)',
    branch: 'Audio System › MEMS Microphone',
    kind: 'hardware',
    func: 'Second microphone positioned 38 mm away from MIC1 to capture the ambient noise field for reference.',
    loc: 'Main PCB, top side, front-left (X = −9.0 mm, Z = +13.0 mm).',
    role: 'Supplies the noise reference the suppression algorithm needs to separate environmental noise from near-field voice.',
    details: [
      'Matched MEMS microphone, same part as MIC1 (gain-matched pair)',
      'Independent acoustic channel and mesh, sealed from MIC1',
      'Phase / level matched within ±1 dB, ±5° across the band',
      'Enables differential / beamforming noise estimation',
    ],
    focus: F(-0.9, 1.0, 1.3, [0.7, 1.0, 0.9]),
  },
  'acoustic-gasket': {
    name: 'ACOUSTIC GASKETS',
    branch: 'Audio System › Sealing',
    kind: 'hardware',
    func: 'Compressible silicone grommets that seal each microphone port to the lid’s acoustic channel and isolate it from internal cavity noise.',
    loc: 'Between the microphone package top face and the acoustic channel, Y = +5.4 … +6.6 mm.',
    role: 'Prevent internal cavity resonance, vibration-borne noise and pressure leakage from corrupting the microphone signal.',
    details: [
      'Silicone, 30 Shore A, Ø 5.0 mm × 1.2 mm, 2 off',
      '0.9 mm concentric sound bore',
      '≈ 0.3 mm compression when the lid is fitted',
    ],
    focus: F(2.72, 0.7, 1.3, [0.9, 0.9, 0.9]),
  },
  'acoustic-duct': {
    name: 'ACOUSTIC CHANNELS',
    branch: 'Audio System › Acoustic Channel',
    kind: 'hardware',
    func: 'Short, smooth-walled ducts moulded into the lid that carry sound from the external ports down to each microphone.',
    loc: 'Inside the lid, from Y = +6.6 mm to the top-face port at Y = +12.5 mm.',
    role: 'Define the acoustic path length and volume, which sets the low-frequency response and the directionality of each microphone.',
    details: [
      'Milled / moulded channel, Ø 1.8 mm, length 6.0 mm',
      'Draft-free straight bore – no 90° bends (avoids resonances)',
      'Front cavity volume 2.1 mm³ (matches mic datasheet)',
    ],
    focus: F(2.72, 0.95, 1.3, [0.9, 1.0, 0.9]),
  },
  'acoustic-mesh': {
    name: 'PROTECTIVE ACOUSTIC MESH',
    branch: 'Audio System › Protective Mesh',
    kind: 'hardware',
    func: 'Stainless micro-mesh screen over each external port; blocks dust, sand, water droplets and debris while passing the audio band.',
    loc: 'At the outer end of each acoustic channel, just below the top surface (Y = +12.8 mm).',
    role: 'The environmental barrier for the acoustic path – essential for a device used in dust, mud and rain.',
    details: [
      '316L stainless woven mesh, 40 µm aperture, 2 off',
      'Backed by a hydrophobic ePTFE membrane',
      '< 1 dB insertion loss below 10 kHz',
      'Captured by a pressed stainless retaining ring',
    ],
    focus: F(2.72, 1.3, 1.3, [0.9, 1.2, 0.9]),
  },
  'audio-harness': {
    name: 'INTERNAL AUDIO HARNESS',
    branch: 'Internal Wiring',
    kind: 'hardware',
    func: 'Short 4-conductor harness from the panel-mounted audio connector to PCB header J2.',
    loc: 'Inside the lower shell, +X side, from the connector bay to the PCB at (X = +28 mm, Z = −3 mm).',
    role: 'Carries the analogue transmit audio and PTT sense between the sealed panel connector and the PCB.',
    details: [
      '4 × 28 AWG, shielded pair for TX_AUDIO, overall drain wire',
      'Length 42 mm, captive in the frame cable channel',
      'Crimped micro contacts in a 4-way housing',
    ],
    focus: F(3.0, 0.5, 0.1, [1.0, 0.7, 0.9]),
  },

  /* ================= CONTROLS ================= */
  'sos-button': {
    name: 'SOS BUTTON',
    branch: 'Controls › SOS',
    kind: 'hardware',
    func: 'Emergency alert / control input.',
    loc: 'External enclosure (top face, left-rear) / control area of the main PCB.',
    role: 'Dedicated, unmistakable emergency input. A long / guarded press flags an emergency condition to the host radio and latches the SOS indicator.',
    specs: {
      dimensions: 'Ø 10.0 mm cap, 2.8 mm recess depth inside bezel',
      material: 'Silicone elastomer over Omron B3F-class sealed tactile switch',
      interface: 'Direct GPIO interrupt (wake from ESP32 deep sleep)',
      package: 'IP67 dust/water immersion sealed, 1,000,000 cycle rating',
    },
    details: [
      'Ø 10.0 mm recessed cap, 2.6 N … 4.5 N actuation force',
      'Recessed 2.8 mm below the raised guard bezel',
      'Sealed IP67 tactile switch, 1 M cycle life',
      'Requires a 1.2 s deliberate press – rejects accidental hits',
      'Independent PCB track direct to the ESP32 (wake-from-sleep)',
      'High-visibility red-orange cap, night-vision readable marking',
    ],
    focus: F(-2.35, 1.25, -0.85, [0.6, 1.3, 0.9]),
  },
  'mark-button': {
    name: 'MARK BUTTON',
    branch: 'Controls › MARK',
    kind: 'hardware',
    func: 'Captures a short audio / event segment for later transmission or reporting.',
    loc: 'External enclosure (top face, left-front) / control area of the main PCB.',
    role: 'Tags the last (and following) N seconds of processed audio and stores it in flash for later replay or transmission through the host radio.',
    specs: {
      dimensions: 'Ø 8.0 mm tactile cap with anti-slip cross ribs',
      material: 'Glass-filled nylon cap over sealed dome switch',
      interface: 'Interrupt GPIO to ESP32 event queue (10s pre / 20s post buffer)',
      package: 'IP67 sealed, 2.0 N actuation force with positive snap feedback',
    },
    details: [
      'Ø 8.0 mm recessed cap, tactile, 2.0 N actuation force',
      'Physically distinct from SOS: smaller, grey, ribbed cap, different bezel height',
      'Short press = tag event, double press = mark + 10 s clip',
      'Captures 10 s pre-roll + 20 s post-roll at 16 kHz ADPCM',
      'Clips queued for transmission when the channel is free',
    ],
    focus: F(-2.35, 1.2, 0.45, [0.6, 1.3, 0.9]),
  },
  'power-switch': {
    name: 'POWER / MODE SWITCH',
    branch: 'Controls › Power',
    kind: 'hardware',
    func: 'Rugged recessed slide switch that isolates the battery and selects the operating mode (OFF / ON / SERVICE).',
    loc: 'Top face, rear-left of the indicator window; switch body on the main PCB.',
    role: 'Allows the module to be hard-powered down for transport and switched into service mode for USB configuration.',
    details: [
      '3-position slide switch, recessed knob with raised ribs',
      'Breaks the battery path before the regulator (zero standby drain)',
      'Glove-operable 9 × 6 mm knob, 4 N detent force',
      'Positively keyed – cannot be moved unintentionally',
    ],
    focus: F(-1.0, 1.3, -1.75, [0.6, 1.3, 1.0]),
  },

  /* ================= POWER ================= */
  battery: {
    name: 'LI-ION BATTERY PACK',
    branch: 'Power › Battery',
    kind: 'hardware',
    func: 'Single-cell lithium-ion pouch pack providing standalone operation of the module for a full mission.',
    loc: 'Battery compartment in the lower shell, beneath the internal frame, Y = −9.8 … −4.2 mm.',
    role: 'Makes SHIELD-COM a self-contained add-on: it does not draw power from the host radio.',
    specs: {
      dimensions: '42.0 × 28.0 × 5.6 mm (standard 503048 pouch)',
      weight: '16.4 g',
      voltage: '3.7 V Nominal (4.20 V max charge, 3.0 V cut-off)',
      material: 'LiCoO2 Lithium-ion cell with integrated safety PCM',
      temperature: 'Charge 0 to +45 °C · Discharge -20 to +60 °C',
      interface: 'JST-PH 2.0 mm 2-pin polarity keyed connector',
    },
    details: [
      '1S1P Li-ion pouch (503048-class), 3.7 V nom., 700 mAh / 2.6 Wh',
      '42 × 28 × 5.6 mm (6.6 cm³ ≈ 400 Wh/L) – 42 % of the internal volume',
      'Integrated PCM protection + 10 kΩ NTC thermistor',
      '≈ 12 h continuous voice-processing runtime at ~210 mW',
      '4.2 mm clearance to the PCB underside, no overlap',
    ],
    focus: F(-0.3, -0.7, 0, [0.9, 0.2, 1.0]),
  },
  'protection-circuit': {
    name: 'BATTERY PROTECTION MODULE (PCM)',
    branch: 'Power › Protection Circuit',
    kind: 'hardware',
    func: 'Cell-level protection: over-charge, over-discharge, over-current and short-circuit disconnect, plus temperature reporting.',
    loc: 'Small PCB bonded to the −X end of the battery pack.',
    role: 'Makes the pack safe to carry, charge and replace in the field.',
    details: [
      'DW01 + dual MOSFET protection, 4.25 V / 2.4 V thresholds',
      '3.5 A over-current trip, 25 mΩ sense',
      '10 kΩ NTC routed to the charger IC',
    ],
    focus: F(-2.46, -0.7, 0, [0.7, 0.3, 1.0]),
  },
  'battery-cable': {
    name: 'BATTERY WIRING',
    branch: 'Internal Wiring',
    kind: 'hardware',
    func: 'Two-conductor cable from the battery PCM to PCB connector J1.',
    loc: 'Routed from the battery compartment, up the +Z cable channel, to the PCB top side.',
    role: 'Delivers cell power and the NTC sense to the power-management section, kept captive so it cannot be pinched by the lid.',
    details: [
      '2 × 24 AWG silicone-insulated leads (red / black)',
      'Length 55 mm, captive in 2 moulded frame clips',
      'Reverse-polarity protected by the polarised J1 shroud',
      'Service loop allows pack replacement without strain',
    ],
    focus: F(-2.55, -0.1, 1.6, [0.7, 0.5, 1.0]),
  },
  'cable-management': {
    name: 'CABLE MANAGEMENT / CLIPS',
    branch: 'Mechanical › Cable Management',
    kind: 'hardware',
    func: 'Moulded clips and channels that hold the battery and audio harnesses away from the battery, the standoffs and the gasket seat.',
    loc: 'Cable channel along the +Z wall of the internal frame.',
    role: 'Keeps all internal wiring organised, non-chafing and clear of the sealing surfaces.',
    details: [
      '2 × snap-fit cable clips on the frame wall',
      'Channel 5.6 mm wide between the PCB edge and the frame',
      'Minimum 6 mm bend radius maintained on all leads',
    ],
    focus: F(2.4, 0.0, 1.9, [1.0, 0.5, 1.0]),
  },

  /* ================= EXTERNAL INTERFACES ================= */
  'radio-cable': {
    name: 'RADIO INTERFACE CABLE',
    branch: 'External Interfaces',
    kind: 'hardware',
    func: 'Moulded 4-pin plug-to-plug cable that carries SHIELD-COM’s processed audio into the accessory port of the existing soldier radio.',
    loc: 'From the +X bay of SHIELD-COM to the host radio accessory connector.',
    role: 'THE add-on link. It makes the relationship unambiguous: SHIELD-COM processes audio, the radio does the RF communication.',
    details: [
      'Module end: 4-pin circular plug, gold contacts, screw coupling ring',
      'Radio end: U-229-style 6-pin audio plug into the radio’s top accessory socket',
      'Over-moulded strain-relief boots at both ends, flex-life tested',
      'Cable: 4 × 28 AWG shielded, PUR jacket, Ø 4.4 mm, ≈ 300 mm long',
      'No RF path – audio and PTT sense only',
    ],
    focus: F(6.0, 12.0, 0.7, [1.0, 0.4, 1.0]),
  },
  'strain-relief': {
    name: 'CABLE STRAIN RELIEF',
    branch: 'Mechanical › Cable Management',
    kind: 'hardware',
    func: 'Over-moulded TPE boot and internal clamp that transfer cable pull and bend loads into the connector body instead of the solder joints.',
    loc: 'Rear of the 4-pin plug on the radio interface cable.',
    role: 'The classic failure point in field audio accessories – solved mechanically rather than electrically.',
    details: [
      'TPE over-mould, 70 Shore A, 26 mm long',
      'Internal tooth clamp on the cable jacket',
      'Tested to 5 000 bend cycles at ±90°, 500 g load',
    ],
    focus: F(4.75, 0.4, 0.55, [1.0, 0.4, 1.0]),
  },
  'host-radio': {
    name: 'EXISTING RADIO (HOST) — TRUE-SCALE REFERENCE',
    branch: 'External Interfaces',
    kind: 'hardware',
    func: 'The soldier VHF handheld that SHIELD-COM attaches to (Radmor 3501-class, as in the reference photo). Modelled at manufacturer datasheet size for scale comparison only — NOT part of SHIELD-COM.',
    loc: 'Standing beside the module, ~30 mm to the right; SHIELD-COM plugs into its top audio / accessory socket.',
    role: 'Shows that the underlying radio remains the primary communication system and owns all RF transmit / receive functions. SHIELD-COM is a 72 mm audio accessory hanging off it.',
    details: [
      'Datasheet size: 230 (H) × 91/75 (W) × 43 (D) mm with battery, no antenna',
      'Mass 940 g with Li-Ion pack · 30.000 – 87.975 MHz · 2 320 channels · 7.2 V',
      'Short flexible whip ≈ 350 mm modelled (a 1 m tape whip is also issued)',
      'Scale vs SHIELD-COM: 3.2× the length, ≈ 7.8× the volume, ≈ 10× the mass',
      'RF transmitter, receiver, antenna, display, keypad, PTT = radio functions',
      'SHIELD-COM adds NO RF transmitter, NO power amplifier and NO antenna',
    ],
    focus: F(10.6, 9.0, 0, [1.0, 0.3, 1.0]),
  },
}

/* ------------------------------------------------------------------ */
/*  Label callouts                                                     */
/* ------------------------------------------------------------------ */
export type LabelDef = {
  id: string
  text: string
  anchor: [number, number, number]
  dir: [number, number, number]
}

export const LABELS: LabelDef[] = [
  { id: 'upper-enclosure', text: 'UPPER ENCLOSURE', anchor: [-0.4, 1.42, 0.2], dir: [-0.2, 1.7, 0.9] },
  { id: 'lower-enclosure', text: 'LOWER ENCLOSURE', anchor: [-1.6, -1.25, -1.4], dir: [-1.9, -1.5, -0.6] },
  { id: 'gasket', text: 'GASKET', anchor: [-3.49, 0.78, -1.2], dir: [-2.6, 0.7, -1.2] },
  { id: 'internal-frame', text: 'INTERNAL FRAME', anchor: [1.2, -0.9, -2.26], dir: [1.6, -1.7, -1.4] },
  { id: 'main-pcb', text: 'MAIN PCB', anchor: [1.3, 0.44, -1.4], dir: [1.4, 1.5, -1.9] },
  { id: 'esp32', text: 'ESP32 PROCESSOR', anchor: [0.55, 0.7, -0.1], dir: [0.4, 2.3, 1.7] },
  { id: 'mic-voice', text: 'MEMS MICROPHONE', anchor: [2.72, 1.3, 1.3], dir: [2.3, 1.9, 1.6] },
  { id: 'audio-adc', text: 'AUDIO CODEC', anchor: [-1.85, 0.53, 0.35], dir: [-2.4, 1.9, 1.1] },
  { id: 'power-mgmt', text: 'POWER MANAGEMENT', anchor: [-2.85, 0.53, -0.3], dir: [-2.8, 1.4, -1.2] },
  { id: 'battery', text: 'BATTERY', anchor: [-0.3, -0.7, 1.4], dir: [-0.6, -2.0, 2.2] },
  { id: 'sos-button', text: 'SOS BUTTON', anchor: [-2.35, 1.3, -0.85], dir: [-3.0, 1.6, -1.6] },
  { id: 'mark-button', text: 'MARK BUTTON', anchor: [-2.35, 1.24, 0.45], dir: [-3.4, 1.1, 1.5] },
  { id: 'status-leds', text: 'STATUS LED', anchor: [1.25, 1.32, -1.86], dir: [1.6, 1.3, -2.6] },
  { id: 'audio-jack', text: 'AUDIO OUTPUT', anchor: [3.5, 0.4, 0.55], dir: [2.2, 1.5, 1.6] },
  { id: 'radio-cable', text: 'RADIO INTERFACE', anchor: [6.0, 8.0, 0.72], dir: [-2.6, 1.4, 1.6] },
  { id: 'mounting-bracket', text: 'MOUNTING BRACKET', anchor: [0.2, -1.4, 1.0], dir: [0.4, -2.2, 1.8] },
  { id: 'host-radio', text: 'SOLDIER RADIO (HOST) · 230 mm', anchor: [14.35, 12.0, 0], dir: [2.6, 1.6, 2.0] },
]

/* ------------------------------------------------------------------ */
/*  System architecture flow                                           */
/* ------------------------------------------------------------------ */
export type FlowNode = {
  label: string
  sub?: string
  kind: 'physical' | 'software' | 'io'
  id?: string
  note?: string
}

export const FLOW: FlowNode[] = [
  { label: 'VOICE', sub: 'operator speech + ambient noise', kind: 'io' },
  { label: 'MEMS MICROPHONE', sub: 'MIC1 voice · MIC2 noise reference', kind: 'physical', id: 'mic-voice' },
  { label: 'AUDIO INPUT', sub: 'gasket · acoustic channel · protective mesh', kind: 'physical', id: 'acoustic-duct' },
  { label: 'ADC / CODEC', sub: 'ES7243-class, 24-bit, I²S out', kind: 'physical', id: 'audio-adc' },
  { label: 'ESP32', sub: 'ESP32-S3-class module, 240 MHz dual core', kind: 'physical', id: 'esp32' },
  { label: 'AI / DSP NOISE SUPPRESSION', sub: 'software: spectral subtraction + adaptive filter + NN VAD', kind: 'software', id: 'esp32' },
  { label: 'VOICE ENHANCEMENT', sub: 'software: AGC · EQ · wind & impulse removal', kind: 'software', id: 'esp32' },
  { label: 'DAC / OUTPUT STAGE', sub: 'ES8156-class DAC + line driver', kind: 'physical', id: 'audio-dac' },
  { label: 'AUDIO OUTPUT', sub: '4-pin circular connector · strain relief', kind: 'physical', id: 'audio-jack' },
  { label: 'RADIO', sub: 'existing soldier radio — RF stays in the radio', kind: 'io', id: 'host-radio' },
]
